In [1]:
#Lets build our own gradient ridge regressor

#import require libraries

import numpy as np

In [6]:
class gradientridge:
    def __init__(self,epoch=500,learning_rate=0.01,alpha=0.1):
        self.epoch=epoch
        self.learning_rate=learning_rate
        self.alpha=alpha
        self.intercept_=None
        self.coef_=None
    
    def fit(self,x_train,y_train):
        x=np.insert(x_train,0,1)
        self.coef_=np.ones(x_train.shape[1])  #coeficients
        self.intercept=0                      #intercept
        thetha=np.insert(self.coef_,0,self.intercept_) #vector of paramters
        
        for i in range(self.epoch):
            gradient=x.T.dot(x).dot(thetha)-np.dot(x.T,y_train)+self.alpha*thetha
            thetha=theta-self.learning_rate*gradient
        self.coef_=thetha[1:]
        self.intercept_=thetha[0]
    
    def predict(self,x_test):
        return self.intercept_+x_test.dot(self.coef_)
        
        
        

In [60]:
class MeraRidgeGD:
    
    def __init__(self,epochs,learning_rate,alpha):
        
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        
        self.coef_ = np.ones(X_train.shape[1])
        self.intercept_ = 0
        thetha = np.insert(self.coef_,0,self.intercept_)
        
        X_train = np.insert(X_train,0,1,axis=1)
        
        for i in range(self.epochs):
            thetha_der = np.dot(X_train.T,X_train).dot(thetha) - np.dot(X_train.T,y_train) + self.alpha*thetha
            thetha = thetha - self.learning_rate*thetha_der
        
        self.coef_ = thetha[1:]
        self.intercept_ = thetha[0]
    
    def predict(self,X_test):
        
        return np.dot(X_test,self.coef_) + self.intercept_

In [3]:
#lets try our model
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
x,y=load_diabetes(return_X_y=True)

C:\Users\shraj\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
x_train,x_test,y_train,y_tets=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
#lets fit pur model

grdnt=gradientridge(epoch=500,learning_rate=0.005,alpha=0.01)
grdnt.fit(x_train,y_train)
grdnt.coef_

AttributeError: 'numpy.float64' object has no attribute 'dot'

In [41]:
np.zeros(1)

array([0.])

In [51]:
x=np.c_[np.ones(x_train.shape[0]),x_train]
coef_=np.ones(x_train.shape[1])
intercept_=0
theta=np.insert(coef_,0,intercept_)

In [52]:
theta

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
x.shape

(353, 11)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
selfcoef_=np.ones(x_train.shape[1])  #coeficients
selfintercept=0                      #intercept
thetha=np.insert(selfcoef_,0,selfintercept)

In [66]:
theta

(11,)